service: serverless-contact
tenant: crashthatch
app: contactus

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource:
        Fn::Join:
          - ":"
          - - "arn:aws:ses"
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - "identity/hello@horizon-explorer.com"

functions:
  contact:
    handler: contactUsLambda.contact
    events:
      - http:
          path: contact
          method: post
          cors: true
